name: Essenciais
version: 1.12.2.0
description: Core plugin for servers.

author: Brunoxkk0

main: br.dev.brunoxkk0.essenciais.Essenciais

depend:
  - SyrxCore
  - EverNifeCore

permissions:
  essenciais.command.teleport.tpa:
    default: true
    description: "Allow /tpa command usage."